services:
   postgres:
    image: postgres:17
    container_name: utd-carpool-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: carpool
      POSTGRES_USER: carpool_user
      POSTGRES_PASSWORD: carpool_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: