spring.application.name=cpool
spring.datasource.url=jdbc:postgresql://localhost:5433/cpool
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.username=cpool_user
spring.datasource.password=cpool_password
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.jdbc=DEBUG
server.port=8081
spring.jpa.hibernate.ddl-auto=none

logging.level.org.hibernate.tool.schema=DEBUG
logging.level.org.hibernate.orm.schema=DEBUG
logging.level.org.hibernate.SQL=DEBUG