spring.application.name=cpool
spring.datasource.url=jdbc:postgresql://localhost:5432/cpool
spring.datasource.username=cpool_user
spring.datasource.password=cpool_password
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG
server.port=8081